name: Deploy Laravel API to Google Cloud 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy Laravel to GCE
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_SSH_KEY }}
        port: 22
        script: |
          # Set non-interactive mode for apt
          export DEBIAN_FRONTEND=noninteractive

          # Ensure necessary dependencies are installed
          sudo apt-get update
          sudo apt-get install -y git unzip php8.2 php8.2-cli php8.2-fpm php8.2-mbstring php8.2-curl php8.2-xml php8.2-mysql php8.2-zip curl

          # Remove existing directory to prevent conflicts
          sudo rm -rf /var/www/lynkly.bigodeals.net
          sudo mkdir -p /var/www/lynkly.bigodeals.net
          sudo chown -R $USER:$USER /var/www/lynkly.bigodeals.net
          sudo chmod -R 775 /var/www/lynkly.bigodeals.net

          # ✅ Authenticate Git using GitHub Token
          echo "🚀 Setting up Git credentials..."
          export GIT_TOKEN=${{ secrets.GH_ACCESS_TOKEN }}
          git config --global credential.helper store
          echo "https://${GIT_TOKEN}:x-oauth-basic@github.com" > ~/.git-credentials

          # ✅ Clone the repository using the token
          echo "🚀 Cloning repository..."
          git clone https://github.com/MlamliLolwane/Soft-Deletes-Cold-Storage-API /var/www/lynkly.bigodeals.net

          # ✅ Set correct permissions
          sudo chown -R www-data:www-data /var/www/lynkly.bigodeals.net/storage
          sudo chmod -R 775 /var/www/lynkly.bigodeals.net/storage

          cd /var/www/lynkly.bigodeals.net || { echo "❌ Directory not found!"; exit 1; }

          # ✅ Now run composer install
          composer install --no-dev --optimize-autoloader -vvv

          php artisan config:clear
          php artisan cache:clear
          php artisan config:cache

          # ✅ Create .env file with correct permissions before writing to it
          echo "🚀 Creating .env file..."
          sudo touch .env
          sudo chmod 660 .env
          sudo chown www-data:www-data .env

          # ✅ Write environment variables to .env file
          echo "🚀 Writing environment variables to .env file..."
          cat <<EOL | sudo tee .env > /dev/null
          APP_NAME=Lynkly
          APP_ENV=production
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=false
          APP_URL=${{ secrets.APP_URL }}
          
          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=${{ secrets.DB_PORT }}
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          
          BROADCAST_DRIVER=log
          CACHE_DRIVER=redis
          FILESYSTEM_DISK=gcs
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          
          MEMCACHED_HOST=${{ secrets.MEMCACHED_HOST }}
          REDIS_CLIENT=predis
          REDIS_HOST=${{ secrets.REDIS_HOST }}
          REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
          REDIS_PORT=${{ secrets.REDIS_PORT }}
          
          GOOGLE_CLOUD_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
          GOOGLE_CLOUD_STORAGE_BUCKET=${{ secrets.GOOGLE_CLOUD_STORAGE_BUCKET }}
          EOL

          # ✅ Double-check file creation
          ls -lah .env
          cat .env

          composer install

          php artisan config:clear
          php artisan cache:clear
          php artisan migrate --force
          php artisan queue:restart &&
          php artisan schedule:run

          # ✅ Restart services
          sudo systemctl restart php8.2-fpm
          sudo systemctl restart nginx
